package com.example.androidphysicslab;

public class Languages
{
    public static String logIn;
    public static String freeFall;
    public static String start;
    public static String mass;
    public static String height;
    public static String planet;
    public static String mercury;
    public static String venus;
    public static String earth;
    public static String moon;
    public static String mars;
    public static String phobos;
    public static String deimos;
    public static String jupiter;
    public static String ganymede;
    public static String callisto;
    public static String io;
    public static String europa;
    public static String himalia;
    public static String amalthea;
    public static String saturn;
    public static String titan;
    public static String rhea;
    public static String iapetus;
    public static String dione;
    public static String tethys;
    public static String uranus;
    public static String neptune;
    public static String pluto;
    public static String[] planets;
    public static double[] gravity={3.73, 8.87, 9.807, 1.62, 3.721, 0.0057, 0.03, 24.7, 1.42, 1.236, 1.796, 1.315, 0.062, 0.02, 10.44, 1.352, 0.264, 0.223, 0.232, 0.145, 8.87, 11.5, 0.62};
    public static String whatIsTheGravityOfEarth;
    public static String heightTime;
    public static String velocityTime;
    public static String plots;
    public static String backToMenu;
    public static String back;
    public static String emailAddress;
    public static String password;
    public static String signIn;
    public static String spring;
    public static String results;
    public static String credits;
    public static String logOut;
    public static String springConstant;
    public static String xTime;
    public static String aTime;
    public static String secondNewtonsLaw;
    public static String mass1;
    public static String mass2;
    public static String friction;
    public static String experiments;
    public static String other;
    public static String positionTime;
    public static String voltageExperiment;
    public static String epsilon;
    public static String internalR;
    public static String maxR;
    public static String iVPlot;
    public static String discExperiment;
    public static String elasticConstant;
    public static String shiftDistance;
    public static String collision;
    public static String distanceTime;
    public static String railHeight;
    public static String tableHeight;
    public static String galvanometer;
    public static String n;
    public static String area;
    public static String tgI;
    public static String backToAnimation;
    public static String enterAsGuest;
    public static String guest;
    public static String amplitude;
    public static String periods;
    public static String createExcel;
    public static String choseFileName;
    public static String save;
    public static String cancel;
    public static String clickToStart;

    public static void toEnglish()
    {
        logIn="Sign In";
        freeFall="Free Fall";
        start="Start";
        mass="Mass (kg)";
        height="Height (m)";
        planet="Planet";
        mercury="Mercury";
        venus="Venus";
        earth="Earth";
        moon="      The Moon";
        mars="Mars";
        phobos="      Phobos";
        deimos="      Deimos";
        jupiter="Jupiter";
        ganymede="      Ganymede";
        callisto="      Callisto";
        io="      Io";
        himalia="      Himalia";
        europa="      Europa";
        amalthea="      Amalthea";
        saturn="Saturn";
        titan="      Titan";
        rhea="      Rhea";
        iapetus="      Iapetus";
        dione="      Dione";
        tethys="      Tethys";
        uranus="Uranus";
        neptune="Neptune";
        pluto="Pluto";
        planets=new String[]{mercury, venus, earth, moon, mars, phobos, deimos, jupiter, ganymede, callisto, io, europa, himalia, amalthea, saturn, titan, rhea, iapetus, dione, tethys, uranus, neptune, pluto};
        whatIsTheGravityOfEarth="You have chosen Planet Earth. Do you want to substitute g=10 or g=9.807?";
        heightTime="Height as function of time";
        velocityTime="Velocity as function of time";
        plots="Plots";
        backToMenu="Back to menu";
        back="Back";
        emailAddress="Email address";
        password="Password";
        signIn="Log In";
        spring="Spring";
        results="Results";
        credits="Credits";
        logOut="Log out";
        springConstant="Spring Constant (N/m)";
        aTime="Acceleration as function of time";
        xTime="length as function of time";
        secondNewtonsLaw="2nd Newton's Law";
        mass1="Mass on desk (kg)";
        mass2="Mass in air (kg)";
        friction="Coefficient of friction";
        experiments="Experiments";
        other="Other";
        positionTime="Position as a function of time";
        voltageExperiment="Voltage Experiment";
        epsilon="Electromotive Force (Volt)";
        internalR="Internal Resistannce (Ohm)";
        maxR="Maximum resistance (Ohm)";
        iVPlot="Voltage as a function of Current";
        discExperiment="Disc Experiment";
        elasticConstant="Elastic Constant (N/m)";
        shiftDistance="Shift Distance (m)";
        collision="2D collision";
        distanceTime="Distance as a function of time";
        railHeight="Rail height (m)";
        tableHeight="Table height (m)";
        galvanometer="Tangent Galvanometer";
        n="Number of windings";
        area="Area (m^2)";
        tgI="tg(θ) as function of current";
        backToAnimation="Back to animation";
        enterAsGuest="Enter as guest";
        guest="Guest";
        amplitude="Amplitude (meter)";
        periods="Periods";
        createExcel="Create Excel";
        choseFileName="Chose File Name:";
        save="Save";
        cancel="Cancel";
        clickToStart="Press on the screen to start the animation";
    }

    public static void toHebrew()
    {
        logIn="יצירת חשבון";
        freeFall="נפילה חופשית";
        start="התחל";
        mass="מסה (קילוגרם)";
        height="גובה (מטר)";
        planet="כוכב לכת";
        mercury="כוכב חמה/מרקורי";
        venus="נוגה/ונוס";
        earth="כדור הארץ";
        moon="      הירח";
        mars="מאדים";
        phobos="      פובוס";
        deimos="      דימוס";
        jupiter="צדק/יופיטר";
        ganymede="      גנימד";
        callisto="      קליסטו";
        io="      איו";
        himalia="      הימליה";
        europa="      אירופה";
        amalthea="      אמלתאה";
        saturn="שבתאי";
        titan="      טיטן";
        rhea="      ריאה";
        iapetus="      יאפטוס";
        dione="      דיוני";
        tethys="      טתיס";
        uranus="אורנוס";
        neptune="נפטון";
        pluto="פלוטו";
        planets=new String[]{mercury, venus, earth, moon, mars, phobos, deimos, jupiter, ganymede, callisto, io, europa, himalia, amalthea, saturn, titan, rhea, iapetus, dione, tethys, uranus, neptune, pluto};
        whatIsTheGravityOfEarth="בחרת בכדור הארץ. האם ברצונך להציב בתור תאוצת הכבידה של כדור הארת 9.807 או 10?";
        heightTime="גובה כפונקציה של זמן";
        velocityTime="מהירות כפונקציה של זמן";
        plots="גרפים";
        backToMenu="חזור לתפריט";
        back="חזור";
        emailAddress="כתובת אימייל";
        password="סיסמא";
        signIn="התחברות";
        spring="קפיץ";
        results="תוצאות";
        credits="קרדיטים";
        logOut="התנתקות";
        springConstant="קבוע הקפיץ (ניוטון/מטר)";
        aTime="תאוצה כפונקציה של זמן";
        xTime="אורך כפונקציה של זמן";
        secondNewtonsLaw="החוק השני של ניוטון";
        mass1="מסה על שולחן (קילוגרם)";
        mass2="מסה באוויר (קילוגרם)";
        friction="מקדם חיכוך";
        experiments="ניסויים";
        other="אחר";
        positionTime="מיקום כפונקציה של זמן";
        voltageExperiment="ניסוי מתח";
        epsilon="כוח אלקטרומניע (וולט)";
        internalR="התנגדות פנימית (אום)";
        maxR="התנגדות מקסימלית (אום)";
        iVPlot="מתח כפונקציה של זרם";
        discExperiment="ניסוי דיסקה";
        elasticConstant="קבוע אלסטי (ניוטון/מטר)";
        shiftDistance="מרחק הסתה (מטר)";
        collision="התנגשות בשני מימדים";
        distanceTime="מרחק כפונקציה של זמן";
        railHeight="גובה מסילה (מטר)";
        tableHeight="גובה שולחן (מטר)";
        galvanometer="גלוונומטר טנגטי";
        n="מספר ליפופים";
        area="שטח (מ^2)";
        tgI="tg(θ) כפונקציה של זרם";
        backToAnimation="חזור לאנימציה";
        enterAsGuest="כניסה בתור אורח";
        guest="אורח";
        amplitude="אמפליטודה (מטר)";
        periods="מחזורים";
        createExcel="יצירת קובץ אקסאל";
        choseFileName="בחר שם קובץ:";
        save="שמירה";
        cancel="ביטול";
        clickToStart="לחץ על המסך על מנת להתחיל את האנימציה";
    }
}
